name:                fwacsv
version:             0.1.0.0
github:              "peteryland/fwacsv"
license:             BSD3
author:              "Pete Ryland"
maintainer:          "pdr@pdr.cx"
copyright:           "(c) 2019 Pete Ryland"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Tools

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/peteryland/fwacsv#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - bytestring >= 0.10
  - binary >= 0.8
  - time >= 1.8
  - utf8-string >= 1.0

executables:
  fwacsv:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - fwacsv

tests:
  fwacsv-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - fwacsv
